function result = test_ros_flat_contract()
%TEST_ROS_FLAT_CONTRACT Verify MATLAB parsing of the standard ROS bridge topics.

thisFile = mfilename('fullpath');
matlabRoot = fileparts(fileparts(thisFile));
addpath(matlabRoot);
dynamics = [ ...
    4.0, 0.02, 1.0, ...
    0.90, 0.01, 0.02, 0.95, ...
    0.30, 1.10, 0.01, 0.20, 1.20, 1.70, ...
    0.78, 0.66, 0.02, 0.03, 0.06, 0.13 ...
];
tracking = [1.0, 42.0, 0.20, 0.05, 0.10, 0.40, 4.5, 0.08, 0.36, 0.60];
appliedSteering = [1.0, 42.0, -0.031];
packet = neurogrip.parse_dynamics_flat(dynamics);
assert(packet.valid, 'A valid C2 compatibility packet was rejected.');
assert(max(abs(packet.a_lateral - [0.90, 0.01; 0.02, 0.95]), [], 'all') < 1e-14, ...
    'Row-major C2 A matrix was decoded incorrectly in MATLAB.');
assert(max(abs(packet.b_lateral - [0.30; 1.10]), [], 'all') < 1e-14, ...
    'C2 B vector was decoded incorrectly in MATLAB.');
assert(packet.schema_version == uint32(4) && ...
    abs(packet.estimated_front_grip - 0.78) < 1e-14 && ...
    abs(packet.estimated_rear_grip - 0.66) < 1e-14 && ...
    abs(packet.front_grip_std - 0.02) < 1e-14 && ...
    abs(packet.rear_grip_std - 0.03) < 1e-14 && ...
    abs(packet.front_grip_error_q90 - 0.06) < 1e-14 && ...
    abs(packet.rear_grip_error_q90 - 0.13) < 1e-14, ...
    'Schema-4 grip/uncertainty fields were decoded incorrectly.');
busType = neurogrip.dynamics_model_bus_type();
expectedBusNames = { ...
    'schema_version', 'sample_time_s', 'a_lateral', 'b_lateral', ...
    'ensemble_std', 'conformal_radius', 'ood_score', 'latency_ms', ...
    'estimated_front_grip', 'estimated_rear_grip', ...
    'front_grip_std', 'rear_grip_std', ...
    'front_grip_error_q90', 'rear_grip_error_q90'};
assert(isequal({busType.Elements.Name}, expectedBusNames), ...
    'Schema-4 Simulink input bus field order differs from the wire contract.');
state = neurogrip.parse_tracking_state_flat(tracking);
assert(state.valid && abs(state.v_x_mps - 4.5) < 1e-14, ...
    'A valid tracking compatibility packet was rejected.');
applied = neurogrip.parse_applied_steering_flat(appliedSteering);
assert(applied.valid && abs(applied.steering_rad + 0.031) < 1e-14, ...
    'A valid measured-steering compatibility packet was rejected.');
update = neurogrip.prepare_adaptive_model_update(dynamics, tracking);
assert(update.valid, 'Valid C2/tracking packets did not produce an Adaptive MPC update.');
assert(isequal(size(update.model_bus.A), [4, 4, 31]), ...
    'ROS-prepared Adaptive MPC A bus has the wrong dimensions.');
assert(max(abs(update.model_bus.A(:, :, 1) - update.model_bus.A(:, :, end)), [], 'all') == 0.0, ...
    'Static C2 packet should be repeated exactly across the model horizon.');

invalidDynamics = dynamics;
invalidDynamics(3) = 0.0;
invalidUpdate = neurogrip.prepare_adaptive_model_update(invalidDynamics, tracking);
assert(~invalidUpdate.valid && strcmp(invalidUpdate.reason, 'dynamics_marked_invalid'), ...
    'An invalid C2 packet was not rejected safely.');
truncatedSchema4 = dynamics(1:13);
truncatedPacket = neurogrip.parse_dynamics_flat(truncatedSchema4);
assert(~truncatedPacket.valid && strcmp(truncatedPacket.reason, 'invalid_dynamics_length'), ...
    'A schema-4 packet missing grip fields was not rejected safely.');
legacySchema2 = dynamics(1:13);
legacySchema2(1) = 2.0;
legacyPacket = neurogrip.parse_dynamics_flat(legacySchema2);
assert(legacyPacket.valid && isnan(legacyPacket.estimated_front_grip), ...
    'The documented legacy schema-2 compatibility path is broken.');
invalidTracking = tracking(1:end - 1);
invalidUpdate = neurogrip.prepare_adaptive_model_update(dynamics, invalidTracking);
assert(~invalidUpdate.valid && strcmp(invalidUpdate.reason, 'invalid_tracking_length'), ...
    'A malformed tracking packet was not rejected safely.');
invalidAppliedSteering = appliedSteering;
invalidAppliedSteering(3) = 0.38;
invalidApplied = neurogrip.parse_applied_steering_flat(invalidAppliedSteering);
assert(~invalidApplied.valid && strcmp(invalidApplied.reason, 'applied_steering_out_of_bounds'), ...
    'Out-of-bounds measured steering was not rejected safely.');
result = struct('model_pages', size(update.model_bus.A, 3), ...
    'lift_speed_mps', state.v_x_mps);
fprintf('ROS_FLAT_CONTRACT_PASS pages=%d vx_mps=%.3f\n', ...
    result.model_pages, result.lift_speed_mps);
end
