function test_latency_compensated_mpc_move()
%TEST_LATENCY_COMPENSATED_MPC_MOVE Verify the explicit one-step predictor.

frame = struct( ...
    'previous_steering_rad', 0.02, ...
    'v_x_mps', 8.0, ...
    'curvature_preview', 0.01 * ones(30, 1), ...
    'left_corridor_preview', 1.5 * ones(30, 1), ...
    'right_corridor_preview', 1.5 * ones(30, 1), ...
    'state', [0.1; -0.02; 0.03; -0.01], ...
    'a_tracking', diag([1.0, 1.0, 0.95, 0.95]), ...
    'b_tracking', [0.0, 0.0; 0.01, -0.02; 0.1, 0.0; 0.2, -0.1], ...
    'sample_time_s', 0.02 ...
);
expectedState = frame.a_tracking * frame.state + frame.b_tracking * [ ...
    frame.previous_steering_rad; ...
    frame.v_x_mps * frame.curvature_preview(1) ...
];
result = neurogrip.latency_compensated_mpc_move(frame, 'mpc-active-set');
assert(result.delay_compensation_steps == 1);
assert(max(abs(result.delay_compensated_state - expectedState)) < 1e-12);
assert(isfinite(result.first_move_rad));
assert(abs(result.first_move_rad) <= 0.37);
fprintf('MATLAB_LATENCY_COMPENSATION_TEST_PASS\n');
end
