function result = test_adaptive_model_bus_contract()
%TEST_ADAPTIVE_MODEL_BUS_CONTRACT Verify C2-physical-model-to-MPC mapping.

thisFile = mfilename('fullpath');
matlabRoot = fileparts(fileparts(thisFile));
repositoryRoot = fileparts(matlabRoot);
addpath(matlabRoot);
fit = neurogrip.load_nominal_fit(fullfile(repositoryRoot, 'runs', ...
    'eufs_v1', 'models', 'nominal_fit.json'));
[aReference, bReference, aLateral, bLateral] = ...
    neurogrip.build_tracking_plant(4.5, fit, 0.02);
[aLifted, bLifted] = neurogrip.build_tracking_plant_from_lateral( ...
    4.5, aLateral, bLateral, 0.02);
assert(max(abs(aReference - aLifted), [], 'all') <= 1e-14, ...
    'The C2 physical A matrix does not lift to the nominal MPC tracking model.');
assert(max(abs(bReference - bLifted), [], 'all') <= 1e-14, ...
    'The C2 physical B matrix does not lift to the nominal MPC tracking model.');

modelBus = neurogrip.make_adaptive_model_bus(aLifted, bLifted);
expectedNames = {'A', 'B', 'C', 'D', 'X', 'Y', 'U', 'DX'};
assert(isequal(fieldnames(modelBus), expectedNames'), ...
    'Adaptive MPC model-bus field names differ from the documented contract.');
assert(isequal(size(modelBus.A), [4, 4, 31]) && isequal(size(modelBus.B), [4, 2, 31]), ...
    'Adaptive MPC model-bus state/input dimensions are invalid.');
assert(isequal(size(modelBus.C), [4, 4, 31]) && isequal(size(modelBus.D), [4, 2, 31]), ...
    'Adaptive MPC model-bus output dimensions are invalid.');
assert(isequal(size(modelBus.X), [4, 1, 31]) && isequal(size(modelBus.Y), [4, 1, 31]) && ...
    isequal(size(modelBus.U), [2, 1, 31]) && isequal(size(modelBus.DX), [4, 1, 31]), ...
    'Adaptive MPC model-bus offset-vector dimensions are invalid.');
assert(all(structfun(@(value) all(isfinite(value), 'all'), modelBus)), ...
    'Adaptive MPC model-bus contains a non-finite value.');

busType = neurogrip.adaptive_model_bus_type();
assert(isequal({busType.Elements.Name}, expectedNames), ...
    'Simulink bus type does not preserve the Adaptive MPC field order.');
assert(isequal([busType.Elements.Dimensions], ...
    [4 4 31 4 2 31 4 4 31 4 2 31 4 1 31 4 1 31 2 1 31 4 1 31]), ...
    'Simulink bus type has an unexpected matrix/vector dimension.');
result = struct('field_count', numel(expectedNames), ...
    'max_lift_error', max([max(abs(aReference - aLifted), [], 'all'), ...
        max(abs(bReference - bLifted), [], 'all')]));
fprintf('ADAPTIVE_MODEL_BUS_CONTRACT_PASS fields=%d max_lift_error=%.3e\n', ...
    result.field_count, result.max_lift_error);
end
