function result = test_schema4_policy_parity()
%TEST_SCHEMA4_POLICY_PARITY Verify MATLAB against frozen Python release vectors.

thisFile = mfilename('fullpath');
matlabRoot = fileparts(fileparts(thisFile));
repositoryRoot = fileparts(matlabRoot);
addpath(matlabRoot);
golden = jsondecode(fileread(fullfile(matlabRoot, 'data', ...
    'schema4_policy_golden_v1.json')));
assert(golden.schema_version == 1 && golden.mpc_horizon == 30 && ...
    golden.steering_rate_limit_rad_s == 2.5, ...
    'Schema-4 golden artifact does not describe the release controller.');

filteredFront = 1.0;
filteredRear = 1.0;
frontStd = 0.0;
rearStd = 0.0;
frontQ90 = 0.0;
rearQ90 = 0.0;
ready = false;
policyError = 0.0;
for index = 1:numel(golden.policy_vectors)
    vector = golden.policy_vectors(index);
    observable = neurogrip.grip_is_observable( ...
        vector.vx_mps, vector.yaw_rate_rps, vector.applied_steering_rad);
    assert(observable == vector.observable, ...
        'MATLAB observability gate differs from Python at vector %d.', index);
    if observable
        [filteredFront, filteredRear] = neurogrip.update_filtered_grip( ...
            filteredFront, filteredRear, vector.estimated_front_grip, ...
            vector.estimated_rear_grip, golden.grip_filter_alpha);
        frontStd = vector.front_grip_std;
        rearStd = vector.rear_grip_std;
        frontQ90 = vector.front_grip_error_q90;
        rearQ90 = vector.rear_grip_error_q90;
        ready = true;
    end
    [effective, front, rear] = neurogrip.conservative_grip_policy( ...
        filteredFront, filteredRear, frontStd, rearStd, frontQ90, rearQ90, ...
        golden.grip_error_margin_scale);
    errors = abs([ ...
        filteredFront - vector.expected_filtered_front_grip, ...
        filteredRear - vector.expected_filtered_rear_grip, ...
        frontStd - vector.expected_held_front_std, ...
        rearStd - vector.expected_held_rear_std, ...
        frontQ90 - vector.expected_held_front_error_q90, ...
        rearQ90 - vector.expected_held_rear_error_q90, ...
        front - vector.expected_front_grip, ...
        rear - vector.expected_rear_grip, ...
        effective - vector.expected_effective_grip ...
    ]);
    policyError = max(policyError, max(errors));
    assert(ready == vector.expected_ready, ...
        'MATLAB schema-4 ready state differs from Python at vector %d.', index);
end
assert(policyError < 1e-13, ...
    'Schema-4 EMA/uncertainty policy differs from Python golden vectors.');

safetyError = 0.0;
for index = 1:numel(golden.tracking_safety_vectors)
    vector = golden.tracking_safety_vectors(index);
    actual = neurogrip.tracking_safety_speed_scale( ...
        vector.lateral_error_m, vector.heading_error_rad);
    safetyError = max(safetyError, abs(actual - vector.expected_scale));
end
assert(safetyError < 1e-14, ...
    'Tracking recovery speed scale differs from Python golden vectors.');

profileError = 0.0;
for index = 1:numel(golden.speed_profile_vectors)
    vector = golden.speed_profile_vectors(index);
    profile = neurogrip.build_speed_profile( ...
        vector.s_m(:), vector.length_m, vector.curvature_1pm(:), ...
        vector.friction_coefficient, vector.lateral_utilisation, ...
        vector.maximum_speed_mps, vector.minimum_speed_mps, ...
        vector.acceleration_limit_mps2, vector.braking_limit_mps2, vector.passes);
    profileError = max(profileError, max(abs( ...
        profile.speed_mps(:) - vector.expected_speed_mps(:))));
    profileError = max(profileError, abs( ...
        profile.lateral_limit_mps2 - vector.expected_lateral_limit_mps2));
    for queryIndex = 1:numel(vector.queries)
        actual = neurogrip.speed_at_progress(profile, vector.queries(queryIndex));
        profileError = max(profileError, abs( ...
            actual - vector.expected_query_speed_mps(queryIndex)));
    end
end
assert(profileError < 1e-12, ...
    'Periodic speed profile differs from Python golden vectors.');

fit = neurogrip.load_nominal_fit(fullfile(repositoryRoot, 'runs', ...
    'eufs_v1', 'models', 'nominal_fit.json'));
matrixError = 0.0;
moveError = 0.0;
fastMoveError = 0.0;
moveVectors = golden.model_and_move_vectors;
assert(numel(moveVectors) >= 20, ...
    'Schema-4 parity requires at least twenty model/control vectors.');
for index = 1:numel(moveVectors)
    vector = moveVectors(index);
    adaptiveFit = fit;
    adaptiveFit.front_cornering_stiffness_n_rad = ...
        fit.front_cornering_stiffness_n_rad * vector.filtered_front_grip;
    adaptiveFit.rear_cornering_stiffness_n_rad = ...
        fit.rear_cornering_stiffness_n_rad * vector.filtered_rear_grip;
    [aTracking, bTracking] = neurogrip.build_tracking_plant( ...
        vector.vx_mps, adaptiveFit, golden.sample_time_s);
    matrixError = max(matrixError, max(abs( ...
        aTracking - vector.a_tracking), [], 'all'));
    matrixError = max(matrixError, max(abs( ...
        bTracking - vector.b_tracking), [], 'all'));
    solution = neurogrip.python_equivalent_mpc_move( ...
        vector.state(:), vector.curvature_preview_1pm(:), vector.vx_mps, ...
        aTracking, bTracking, golden.sample_time_s, ...
        vector.previous_steering_rad);
    moveError = max(moveError, abs( ...
        solution.first_move_rad - vector.python_first_move_rad));
    fastSolution = neurogrip.python_equivalent_mpc_move( ...
        vector.state(:), vector.curvature_preview_1pm(:), vector.vx_mps, ...
        aTracking, bTracking, golden.sample_time_s, ...
        vector.previous_steering_rad, double.empty(0, 1), ...
        double.empty(0, 1), 'mpc-active-set');
    fastMoveError = max(fastMoveError, abs( ...
        fastSolution.first_move_rad - vector.python_first_move_rad));
end
assert(matrixError < 1e-10, ...
    'Schema-4 grip-scaled tracking matrices differ from Python.');
assert(moveError < 2e-5, ...
    'MATLAB Python-equivalent first move differs from OSQP golden vectors.');
assert(fastMoveError < 2e-5, ...
    'MATLAB real-time active-set first move differs from OSQP golden vectors.');

result = struct( ...
    'policy_vectors', numel(golden.policy_vectors), ...
    'model_move_vectors', numel(moveVectors), ...
    'max_policy_error', policyError, ...
    'max_safety_error', safetyError, ...
    'max_profile_error', profileError, ...
    'max_matrix_error', matrixError, ...
    'max_first_move_error_rad', moveError, ...
    'max_fast_first_move_error_rad', fastMoveError ...
);
fprintf(['SCHEMA4_POLICY_PARITY_PASS policy=%d model_moves=%d ', ...
    'policy_error=%.3e profile_error=%.3e matrix_error=%.3e ', ...
    'first_move_error=%.3e fast_first_move_error=%.3e\n'], ...
    result.policy_vectors, result.model_move_vectors, ...
    result.max_policy_error, result.max_profile_error, ...
    result.max_matrix_error, result.max_first_move_error_rad, ...
    result.max_fast_first_move_error_rad);
end
