function result = test_programmatic_c0_closed_loop()
%TEST_PROGRAMMATIC_C0_CLOSED_LOOP Verify headless nominal MPC closed-loop run.

thisFile = mfilename('fullpath');
matlabRoot = fileparts(fileparts(thisFile));
addpath(matlabRoot);
modelPath = build_neurogrip_c0_closed_loop(test_model_directory(), 4.5);
[~, modelName] = fileparts(modelPath);
output = sim(modelPath, 'StopTime', '0.4', 'ReturnWorkspaceOutputs', 'on');
states = output.get('tracking_state').signals.values;
moves = output.get('steering_move').signals.values;
assert(all(isfinite(states), 'all') && all(isfinite(moves), 'all'), ...
    'C0 closed-loop simulation contains a non-finite signal.');
assert(all(abs(moves) <= 0.37 + 1e-12, 'all'), ...
    'C0 closed-loop simulation violated the steering bound.');
assert(abs(moves(1)) <= 2.5 * 0.02 + 1e-12, ...
    'C0 closed-loop first move violated the steering-rate limit.');
assert(all(abs(diff(moves)) <= 2.5 * 0.02 + 1e-12, 'all'), ...
    'C0 closed-loop simulation violated the steering-rate limit.');
assert(moves(1) < 0.0, ...
    'C0 closed-loop controller did not command corrective steering for positive e_y/e_psi.');
result = struct( ...
    'model_path', modelPath, ...
    'initial_lateral_error_m', states(1, 1), ...
    'final_lateral_error_m', states(end, 1), ...
    'max_abs_steering_rad', max(abs(moves), [], 'all') ...
);
fprintf(['PROGRAMMATIC_C0_CLOSED_LOOP_PASS initial_e_y=%.6f final_e_y=%.6f ' ...
    'max_abs_steering=%.6f model=%s\n'], result.initial_lateral_error_m, ...
    result.final_lateral_error_m, result.max_abs_steering_rad, result.model_path);
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
