function result = test_programmatic_adaptive_mpc_closed_loop()
%TEST_PROGRAMMATIC_ADAPTIVE_MPC_CLOSED_LOOP Run the typed model bus headlessly.

thisFile = mfilename('fullpath');
matlabRoot = fileparts(fileparts(thisFile));
repositoryRoot = fileparts(matlabRoot);
addpath(matlabRoot);
modelPath = build_neurogrip_adaptive_mpc(test_model_directory(), 4.5);
[~, modelName] = fileparts(modelPath);
load_system(modelPath);
output = sim(modelName, 'StopTime', '0.4', 'ReturnWorkspaceOutputs', 'on');
states = output.get('adaptive_tracking_state').signals.values;
moves = output.get('adaptive_steering_move').signals.values;
assert(all(isfinite(states), 'all') && all(isfinite(moves), 'all'), ...
    'Adaptive MPC bus simulation contains a non-finite signal.');
assert(all(abs(moves) <= 0.37 + 1e-12, 'all'), ...
    'Adaptive MPC bus simulation violated the steering bound.');
assert(abs(moves(1)) <= 2.5 * 0.02 + 1e-12, ...
    'Adaptive MPC bus simulation violated the first steering-rate bound.');
assert(all(abs(diff(moves)) <= 2.5 * 0.02 + 1e-12, 'all'), ...
    'Adaptive MPC bus simulation violated the steering-rate bound.');
assert(moves(1) < 0.0, ...
    'Adaptive MPC bus simulation did not command initial corrective steering.');

% Change only the online model bus to a physically valid asymmetric low-grip
% plant. If the Adaptive MPC model port were decorative or disconnected, the
% steering sequence would remain bit-identical.
fit = neurogrip.load_nominal_fit(fullfile(repositoryRoot, 'runs', ...
    'eufs_v1', 'models', 'nominal_fit.json'));
adaptiveFit = fit;
adaptiveFit.front_cornering_stiffness_n_rad = ...
    0.55 * fit.front_cornering_stiffness_n_rad;
adaptiveFit.rear_cornering_stiffness_n_rad = ...
    0.85 * fit.rear_cornering_stiffness_n_rad;
[adaptiveA, adaptiveB] = neurogrip.build_tracking_plant(4.5, adaptiveFit, 0.02);
adaptiveBus = neurogrip.make_adaptive_model_bus(adaptiveA, adaptiveB);
workspace = get_param(modelName, 'ModelWorkspace');
assignin(workspace, 'onlineA', adaptiveBus.A);
assignin(workspace, 'onlineB', adaptiveBus.B);
adaptiveOutput = sim(modelName, 'StopTime', '0.4', 'ReturnWorkspaceOutputs', 'on');
adaptiveMoves = adaptiveOutput.get('adaptive_steering_move').signals.values;
modelResponseDelta = max(abs(adaptiveMoves - moves), [], 'all');
assert(modelResponseDelta > 1e-5, ...
    'Changing the online A/B model did not change the Adaptive MPC output.');
result = struct( ...
    'model_path', modelPath, ...
    'initial_lateral_error_m', states(1, 1), ...
    'final_lateral_error_m', states(end, 1), ...
    'max_abs_steering_rad', max(abs(moves), [], 'all'), ...
    'online_model_response_delta_rad', modelResponseDelta ...
);
fprintf(['PROGRAMMATIC_ADAPTIVE_MPC_CLOSED_LOOP_PASS initial_e_y=%.6f ' ...
    'final_e_y=%.6f max_abs_steering=%.6f model_delta=%.6f model=%s\n'], ...
    result.initial_lateral_error_m, result.final_lateral_error_m, ...
    result.max_abs_steering_rad, result.online_model_response_delta_rad, ...
    result.model_path);
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
