function result = render_grip_scope_video( ...
    episodeCsvPath, outputVideoPath, replayDurationS, frameRate)
%RENDER_GRIP_SCOPE_VIDEO Replay the final grip estimates through Simulink.
%
% A temporary programmatic Simulink model replays the accepted episode's
% final front/rear estimates through a Scope and To Workspace sink. MATLAB
% then renders the captured Simulink output as a compact five-second panel.

arguments
    episodeCsvPath (1, :) char
    outputVideoPath (1, :) char
    replayDurationS (1, 1) double {mustBePositive, mustBeFinite} = 5.0
    frameRate (1, 1) double {mustBeInteger, mustBePositive} = 30
end

requiredColumns = ["time_s", "estimated_front_grip", ...
    "estimated_rear_grip"];
episode = readtable(episodeCsvPath, 'VariableNamingRule', 'preserve');
assert(all(ismember(requiredColumns, string(episode.Properties.VariableNames))), ...
    'Episode CSV does not contain the required grip-estimate columns.');
lapCompleteS = read_lap_complete_time(episodeCsvPath);
windowStartS = lapCompleteS - replayDurationS;
sourceMask = episode.time_s >= windowStartS & ...
    episode.time_s <= lapCompleteS;
assert(nnz(sourceMask) >= 2, ...
    'Episode does not contain enough samples in the final replay window.');

sourceTime = episode.time_s(sourceMask) - windowStartS;
sourceFront = episode.estimated_front_grip(sourceMask);
sourceRear = episode.estimated_rear_grip(sourceMask);
assert(all(isfinite([sourceTime; sourceFront; sourceRear])), ...
    'Grip replay input contains NaN or Inf.');

replayTime = linspace(0.0, replayDurationS, ...
    round(replayDurationS * frameRate) + 1).';
frontGrip = interp1(sourceTime, sourceFront, replayTime, 'previous', 'extrap');
rearGrip = interp1(sourceTime, sourceRear, replayTime, 'previous', 'extrap');
gripReplayInput = timeseries([frontGrip, rearGrip], replayTime); %#ok<NASGU>

modelName = ['neurogrip_grip_scope_' char(java.util.UUID.randomUUID())];
modelName = strrep(modelName, '-', '_');
new_system(modelName);
modelCleanup = onCleanup(@() close_temporary_model(modelName));
add_block('simulink/Sources/From Workspace', ...
    [modelName '/Accepted C2 telemetry'], ...
    'VariableName', 'gripReplayInput', 'Interpolate', 'on');
add_block('simulink/Sinks/Scope', [modelName '/Grip estimator scope']);
add_block('simulink/Sinks/To Workspace', [modelName '/Captured grip'], ...
    'VariableName', 'capturedGrip', 'SaveFormat', 'Timeseries');
add_line(modelName, 'Accepted C2 telemetry/1', ...
    'Grip estimator scope/1', 'autorouting', 'on');
add_line(modelName, 'Accepted C2 telemetry/1', ...
    'Captured grip/1', 'autorouting', 'on');
set_param(modelName, 'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', sprintf('%.17g', 1.0 / frameRate), ...
    'StartTime', '0.0', ...
    'StopTime', sprintf('%.17g', replayDurationS));
simulationInput = Simulink.SimulationInput(modelName);
simulationInput = simulationInput.setVariable( ...
    'gripReplayInput', gripReplayInput);
simulationOutput = sim(simulationInput);
capturedGrip = simulationOutput.get('capturedGrip');
assert(isa(capturedGrip, 'timeseries') && size(capturedGrip.Data, 2) == 2, ...
    'Simulink replay did not return the two grip signals.');

render_scope_panel(capturedGrip, outputVideoPath, replayDurationS, frameRate);
result = struct( ...
    'source_episode', episodeCsvPath, ...
    'lap_complete_s', lapCompleteS, ...
    'window_start_s', windowStartS, ...
    'duration_s', replayDurationS, ...
    'frame_rate_hz', frameRate, ...
    'frames', round(replayDurationS * frameRate), ...
    'front_min', min(capturedGrip.Data(:, 1)), ...
    'front_max', max(capturedGrip.Data(:, 1)), ...
    'rear_min', min(capturedGrip.Data(:, 2)), ...
    'rear_max', max(capturedGrip.Data(:, 2)), ...
    'output_video', outputVideoPath);
fprintf(['SIMULINK_GRIP_SCOPE_VIDEO_PASS frames=%d duration_s=%.3f ' ...
    'front=[%.4f,%.4f] rear=[%.4f,%.4f] output=%s\n'], ...
    result.frames, result.duration_s, result.front_min, result.front_max, ...
    result.rear_min, result.rear_max, outputVideoPath);
clear modelCleanup;
end

function lapCompleteS = read_lap_complete_time(episodeCsvPath)
[parentDirectory, baseName] = fileparts(episodeCsvPath);
eventsPath = fullfile(parentDirectory, [baseName '.events.jsonl']);
assert(isfile(eventsPath), 'Missing episode event stream: %s', eventsPath);
lines = readlines(eventsPath);
lapCompleteS = NaN;
for index = 1:numel(lines)
    if strlength(strtrim(lines(index))) == 0
        continue;
    end
    event = jsondecode(lines(index));
    if isfield(event, 'event') && strcmp(event.event, 'lap_complete') && ...
            isfield(event, 'safety_valid') && event.safety_valid
        lapCompleteS = double(event.sim_time_s);
    end
end
assert(isfinite(lapCompleteS), ...
    'No safety-valid lap_complete event exists in %s.', eventsPath);
end

function render_scope_panel(grip, outputVideoPath, durationS, frameRate)
background = [0.075, 0.050, 0.035];
panel = [0.105, 0.073, 0.048];
gold = [0.94, 0.78, 0.25];
cyan = [0.16, 0.82, 0.91];
orange = [1.00, 0.47, 0.20];
softWhite = [0.93, 0.91, 0.87];
gridColour = [0.30, 0.25, 0.20];

parentDirectory = fileparts(outputVideoPath);
if ~isempty(parentDirectory) && ~isfolder(parentDirectory)
    mkdir(parentDirectory);
end
figureHandle = figure('Visible', 'off', 'Color', background, ...
    'Position', [100, 100, 960, 760], 'Renderer', 'painters');
figureCleanup = onCleanup(@() close(figureHandle));
axesHandle = axes(figureHandle, 'Position', [0.10, 0.23, 0.86, 0.58], ...
    'Color', panel, 'XColor', softWhite, 'YColor', softWhite, ...
    'GridColor', gridColour, 'GridAlpha', 0.55, ...
    'FontName', 'DejaVu Sans', 'FontSize', 13, 'LineWidth', 1.0);
hold(axesHandle, 'on');
grid(axesHandle, 'on');
box(axesHandle, 'on');
xlim(axesHandle, [0.0, durationS]);
allValues = grip.Data(:);
yMinimum = min(allValues) - 0.025;
yMaximum = max(allValues) + 0.025;
ylim(axesHandle, [yMinimum, yMaximum]);
xlabel(axesHandle, 'TIME IN FINAL LAP SECTOR [s]', ...
    'Color', softWhite, 'FontWeight', 'bold');
ylabel(axesHandle, 'ESTIMATED GRIP  \mu', ...
    'Color', softWhite, 'FontWeight', 'bold');
frontLine = plot(axesHandle, NaN, NaN, 'Color', cyan, ...
    'LineWidth', 3.2, 'DisplayName', 'FRONT AXLE');
rearLine = plot(axesHandle, NaN, NaN, 'Color', orange, ...
    'LineWidth', 3.2, 'DisplayName', 'REAR AXLE');
legendHandle = legend(axesHandle, 'Location', 'southwest', ...
    'TextColor', softWhite, 'Color', panel, 'EdgeColor', gridColour, ...
    'FontWeight', 'bold');
legendHandle.AutoUpdate = 'off';
annotation(figureHandle, 'textbox', [0.10, 0.875, 0.86, 0.07], ...
    'String', 'SIMULINK  /  NEUROGRIP-X GRIP ESTIMATOR', ...
    'Color', softWhite, 'EdgeColor', 'none', 'FontName', 'DejaVu Sans', ...
    'FontWeight', 'bold', 'FontSize', 19, 'Interpreter', 'none');
annotation(figureHandle, 'textbox', [0.10, 0.825, 0.86, 0.05], ...
    'String', 'Accepted C2 lap  |  final 5.0 s  |  causal estimate', ...
    'Color', gold, 'EdgeColor', 'none', 'FontName', 'DejaVu Sans', ...
    'FontWeight', 'bold', 'FontSize', 12, 'Interpreter', 'none');
frontValue = annotation(figureHandle, 'textbox', [0.10, 0.04, 0.39, 0.08], ...
    'String', '', 'Color', cyan, 'EdgeColor', cyan, ...
    'BackgroundColor', panel, 'LineWidth', 1.2, ...
    'FontName', 'DejaVu Sans Mono', 'FontWeight', 'bold', ...
    'FontSize', 16, 'HorizontalAlignment', 'center');
rearValue = annotation(figureHandle, 'textbox', [0.55, 0.04, 0.39, 0.08], ...
    'String', '', 'Color', orange, 'EdgeColor', orange, ...
    'BackgroundColor', panel, 'LineWidth', 1.2, ...
    'FontName', 'DejaVu Sans Mono', 'FontWeight', 'bold', ...
    'FontSize', 16, 'HorizontalAlignment', 'center');

[~, ~, extension] = fileparts(outputVideoPath);
if strcmpi(extension, '.avi')
    videoProfile = 'Motion JPEG AVI';
else
    videoProfile = 'MPEG-4';
end
writer = VideoWriter(outputVideoPath, videoProfile);
writer.FrameRate = frameRate;
writer.Quality = 100;
open(writer);
writerCleanup = onCleanup(@() close(writer));
frameCount = round(durationS * frameRate);
sampleTimes = linspace(0.0, durationS, frameCount);
for frameIndex = 1:frameCount
    nowS = sampleTimes(frameIndex);
    visible = grip.Time <= nowS + 1e-9;
    if ~any(visible)
        visible(1) = true;
    end
    frontNow = interp1(grip.Time, grip.Data(:, 1), nowS, ...
        'previous', 'extrap');
    rearNow = interp1(grip.Time, grip.Data(:, 2), nowS, ...
        'previous', 'extrap');
    set(frontLine, 'XData', grip.Time(visible), ...
        'YData', grip.Data(visible, 1));
    set(rearLine, 'XData', grip.Time(visible), ...
        'YData', grip.Data(visible, 2));
    frontValue.String = sprintf('FRONT  MU = %.3f', frontNow);
    rearValue.String = sprintf('REAR   MU = %.3f', rearNow);
    drawnow;
    writeVideo(writer, getframe(figureHandle));
end
clear writerCleanup figureCleanup;
end

function close_temporary_model(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
