function report = replay_matlab_parity_capture( ...
    capturePath, trackMatPath, nominalFitPath, outputJsonPath)
%REPLAY_MATLAB_PARITY_CAPTURE Validate every recorded C2 controller decision.
%
% The capture is self-contained for controller mathematics. MATLAB rebuilds
% the uncertainty policy, speed profile, blended A/B matrices and Python-
% equivalent QP from each row. No ROS command is published by this function.

arguments
    capturePath (1, :) char {mustBeNonzeroLengthText}
    trackMatPath (1, :) char {mustBeNonzeroLengthText}
    nominalFitPath (1, :) char {mustBeNonzeroLengthText}
    outputJsonPath (1, :) char = ''
end
if ~isfile(capturePath) || ~isfile(trackMatPath) || ~isfile(nominalFitPath)
    error('neurogrip:MissingParityReplayInput', ...
        'Capture, track MAT and nominal fit must all exist.');
end

tableData = readtable(capturePath, 'VariableNamingRule', 'preserve');
values = table2array(tableData);
if ~isnumeric(values) || size(values, 2) ~= 155 || isempty(values)
    error('neurogrip:InvalidParityCapture', ...
        'Parity capture must contain at least one numeric 155-value row.');
end
trackData = load(trackMatPath);
if ~isfield(trackData, 'reference')
    error('neurogrip:InvalidTrackArtifact', ...
        'Track MAT must contain the reference structure.');
end
reference = trackData.reference;
fit = neurogrip.load_nominal_fit(nominalFitPath);

rowCount = size(values, 1);
policyErrors = zeros(rowCount, 1);
targetSpeedErrors = zeros(rowCount, 1);
matrixErrors = zeros(rowCount, 1);
firstMoveErrors = nan(rowCount, 1);
signMismatches = 0;
rateSaturationMismatches = 0;
magnitudeSaturationMismatches = 0;
validSolutionCount = 0;
cachedProfile = [];
cachedKey = nan(1, 6);

for index = 1:rowCount
    frame = neurogrip.parse_matlab_parity_frame(values(index, :));
    if ~frame.valid
        error('neurogrip:InvalidParityCaptureRow', ...
            'Capture row %d is invalid: %s.', index, frame.reason);
    end
    [effectiveGrip, frontGrip, rearGrip] = ...
        neurogrip.conservative_grip_policy( ...
            frame.filtered_grip(1), frame.filtered_grip(2), ...
            frame.held_grip_std(1), frame.held_grip_std(2), ...
            frame.held_grip_error_q90(1), frame.held_grip_error_q90(2), ...
            frame.grip_error_margin_scale);
    policyErrors(index) = max(abs([ ...
        frontGrip - frame.conservative_grip(1), ...
        rearGrip - frame.conservative_grip(2), ...
        effectiveGrip - frame.effective_grip ...
    ]));

    profileKey = [ ...
        round(effectiveGrip, 2), round(frame.profile_utilisation, 3), ...
        frame.maximum_speed_mps, frame.minimum_speed_mps, ...
        frame.acceleration_limit_mps2, frame.braking_limit_mps2 ...
    ];
    if isempty(cachedProfile) || any(profileKey ~= cachedKey)
        cachedProfile = neurogrip.build_speed_profile( ...
            reference.s(:), reference.length, reference.curvature(:), ...
            effectiveGrip, frame.profile_utilisation, ...
            frame.maximum_speed_mps, frame.minimum_speed_mps, ...
            frame.acceleration_limit_mps2, frame.braking_limit_mps2, 4);
        cachedKey = profileKey;
    end
    targetSpeed = neurogrip.speed_at_progress(cachedProfile, frame.lap_progress);
    targetSpeed = targetSpeed * neurogrip.tracking_safety_speed_scale( ...
        frame.state(1), frame.state(2));
    targetSpeed = max(frame.minimum_speed_mps, targetSpeed);
    targetSpeedErrors(index) = abs(targetSpeed - frame.target_speed_mps);

    adaptiveFit = fit;
    adaptiveFit.front_cornering_stiffness_n_rad = ...
        fit.front_cornering_stiffness_n_rad * frame.filtered_grip(1);
    adaptiveFit.rear_cornering_stiffness_n_rad = ...
        fit.rear_cornering_stiffness_n_rad * frame.filtered_grip(2);
    [physicalA, physicalB] = neurogrip.build_tracking_plant( ...
        frame.v_x_mps, adaptiveFit, frame.sample_time_s);
    [learnedA, learnedB] = neurogrip.build_tracking_plant_from_lateral( ...
        frame.v_x_mps, frame.raw_a_lateral, frame.raw_b_lateral, ...
        frame.sample_time_s);
    rebuiltA = physicalA + frame.model_blend * (learnedA - physicalA);
    rebuiltB = physicalB + frame.model_blend * (learnedB - physicalB);
    matrixErrors(index) = max([ ...
        max(abs(rebuiltA - frame.a_tracking), [], 'all'), ...
        max(abs(rebuiltB - frame.b_tracking), [], 'all') ...
    ]);

    if frame.solution_valid
        validSolutionCount = validSolutionCount + 1;
        solution = neurogrip.python_equivalent_mpc_move( ...
            frame.state, frame.curvature_preview, frame.v_x_mps, ...
            rebuiltA, rebuiltB, frame.sample_time_s, ...
            frame.previous_steering_rad, frame.left_corridor_preview, ...
            frame.right_corridor_preview);
        actualMove = solution.first_move_rad;
        expectedMove = frame.first_move_rad;
        firstMoveErrors(index) = abs(actualMove - expectedMove);
        if abs(actualMove) > 1e-5 && abs(expectedMove) > 1e-5 && ...
                sign(actualMove) ~= sign(expectedMove)
            signMismatches = signMismatches + 1;
        end
        rateLimit = 2.5 * frame.sample_time_s;
        % The deployed OSQP accepts a bounded residual and can finish below an
        % active bound. Classify saturation at the same 1e-3 rad acceptance
        % used for solver parity while retaining the raw move error above.
        saturationToleranceRad = 1e-3;
        expectedRateSaturated = abs(expectedMove - frame.previous_steering_rad) >= ...
            rateLimit - saturationToleranceRad;
        actualRateSaturated = abs(actualMove - frame.previous_steering_rad) >= ...
            rateLimit - saturationToleranceRad;
        rateSaturationMismatches = rateSaturationMismatches + ...
            double(expectedRateSaturated ~= actualRateSaturated);
        expectedMagnitudeSaturated = abs(expectedMove) >= ...
            0.37 - saturationToleranceRad;
        actualMagnitudeSaturated = abs(actualMove) >= ...
            0.37 - saturationToleranceRad;
        magnitudeSaturationMismatches = magnitudeSaturationMismatches + ...
            double(expectedMagnitudeSaturated ~= actualMagnitudeSaturated);
    end
end

validMoveErrors = firstMoveErrors(isfinite(firstMoveErrors));
[captureFolder, captureName, captureExtension] = fileparts(capturePath);
captureMetadataPath = fullfile(captureFolder, [captureName, '.metadata.json']);
captureSha256 = '';
if isfile(captureMetadataPath)
    captureMetadata = jsondecode(fileread(captureMetadataPath));
    if isfield(captureMetadata, 'output_sha256')
        captureSha256 = captureMetadata.output_sha256;
    end
end
report = struct( ...
    'schema_version', 1, ...
    'capture_file', [captureName, captureExtension], ...
    'capture_sha256', captureSha256, ...
    'rows', rowCount, ...
    'valid_solution_rows', validSolutionCount, ...
    'max_policy_error', max(policyErrors), ...
    'max_target_speed_error_mps', max(targetSpeedErrors), ...
    'max_matrix_error', max(matrixErrors), ...
    'median_first_move_error_rad', median(validMoveErrors), ...
    'max_first_move_error_rad', max(validMoveErrors), ...
    'sign_mismatches', signMismatches, ...
    'rate_saturation_mismatches', rateSaturationMismatches, ...
    'magnitude_saturation_mismatches', magnitudeSaturationMismatches ...
);

fprintf(['MATLAB_RECORDED_PARITY_RESULT rows=%d valid=%d policy=%.3e ', ...
    'target=%.3e matrix=%.3e move_median=%.3e move_max=%.3e ', ...
    'sign=%d rate_sat=%d magnitude_sat=%d\n'], ...
    report.rows, report.valid_solution_rows, report.max_policy_error, ...
    report.max_target_speed_error_mps, report.max_matrix_error, ...
    report.median_first_move_error_rad, report.max_first_move_error_rad, ...
    report.sign_mismatches, report.rate_saturation_mismatches, ...
    report.magnitude_saturation_mismatches);

assert(report.max_policy_error < 1e-12, ...
    'Recorded schema-4 uncertainty policy does not match MATLAB.');
assert(report.max_target_speed_error_mps < 1e-9, ...
    'Recorded target speed does not match the MATLAB speed profile.');
assert(report.max_matrix_error < 1e-10, ...
    'Recorded A/B model assembly does not match MATLAB.');
assert(report.max_first_move_error_rad < 1e-3 && report.sign_mismatches == 0, ...
    'Recorded first steering moves do not match the MATLAB QP replay.');
assert(report.rate_saturation_mismatches == 0 && ...
    report.magnitude_saturation_mismatches == 0, ...
    'Recorded and replayed steering saturation decisions differ.');

if ~isempty(outputJsonPath)
    outputFolder = fileparts(outputJsonPath);
    if ~isempty(outputFolder) && ~isfolder(outputFolder)
        mkdir(outputFolder);
    end
    fileIdentifier = fopen(outputJsonPath, 'w');
    if fileIdentifier < 0
        error('neurogrip:ParityReportWriteFailure', ...
            'Could not open parity report for writing: %s', outputJsonPath);
    end
    cleanup = onCleanup(@() fclose(fileIdentifier));
    fprintf(fileIdentifier, '%s\n', jsonencode(report, PrettyPrint=true));
end
fprintf(['MATLAB_RECORDED_PARITY_PASS rows=%d valid=%d policy=%.3e ', ...
    'target=%.3e matrix=%.3e move_median=%.3e move_max=%.3e\n'], ...
    report.rows, report.valid_solution_rows, report.max_policy_error, ...
    report.max_target_speed_error_mps, report.max_matrix_error, ...
    report.median_first_move_error_rad, report.max_first_move_error_rad);
end
