function [aTracking, bTracking] = build_tracking_plant_from_lateral( ...
    vxMps, aLateral, bLateral, sampleTimeS)
%BUILD_TRACKING_PLANT_FROM_LATERAL Lift a 2-state physical model for MPC.
%
% The C2 ROS contract publishes a discrete physical lateral model with state
% [v_y; yaw_rate] and steering input.  MPC needs the path-tracking state
% [e_y; e_psi; v_y; yaw_rate] and the measured curvature-rate disturbance
% d_kappa = v_x * curvature.  This function is the sole, explicit lift from
% the C2 contract into that four-state controller model.

arguments
    vxMps (1, 1) double {mustBeFinite}
    aLateral (2, 2) double {mustBeFinite}
    bLateral (2, 1) double {mustBeFinite}
    sampleTimeS (1, 1) double {mustBePositive, mustBeFinite} = 0.02
end

vxMps = max(vxMps, 1.0);
aTracking = [ ...
    1.0, sampleTimeS * vxMps, sampleTimeS, 0.0; ...
    0.0, 1.0, 0.0, sampleTimeS; ...
    0.0, 0.0, aLateral(1, 1), aLateral(1, 2); ...
    0.0, 0.0, aLateral(2, 1), aLateral(2, 2) ...
];
bTracking = [ ...
    0.0, 0.0; ...
    0.0, -sampleTimeS; ...
    bLateral(1), 0.0; ...
    bLateral(2), 0.0 ...
];
end
